spring:
  config:
    import: "configserver:"
  application:
    name: name-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${SERVICE_REGISTRY_URI}