spring:
  config:
    import: "configserver:"
  application:
    name: greeting-service
  profiles:
    active: prod
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${SERVICE_REGISTRY_URI}